dtb-$(CONFIG_ARCH_BCM_IPROC) += stingray-palladium.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += stingray-pd-paxc-chimp.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += stingray-pd-paxb.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += stingray-pd-usb.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += stingray-pd-sata.dtb
